clear;
a=load('2.txt');
figure;
subplot(3, 1, 1);
plot(a(:, 1));
title('xError');
ylabel("inches");
subplot(3, 1, 2);
plot(a(:, 2));
title('yError')
ylabel("inches");
subplot(3, 1, 3);
plot(a(:, 3)*180/3.14159);
title('headingError');
ylabel("degree");
figure;
plot(1:length(a(:, 1)), a(:, 1), a(:, 2));
hold on;
plot(1:length(a(:, 1)), a(:, 3)./3.1416*180);
legend('xError', 'yError', 'headingErr');
figure;
title('x');
x_e = a(:, 1);
x = a(:, 4);
s = x+x_e;
plot(1:length(s), s, x);
ylabel("inches");
legend('target x', 'actual x');
figure;
title('y');
x_e = a(:, 2);
x = a(:, 5);
s = x+x_e;
plot(1:length(s), s, x);
legend('target y', 'actual y');
ylabel("inches");
figure;
title('heading');
x_e = a(:, 3);
x = a(:, 6);
s = x+x_e;
plot(1:length(s), s/pi*180, x/pi*180);
legend('target heading', 'actual heading');
ylabel("degree");